[package]
name = "text-editor-thingy"
version = "0.1.0"
authors = ["jaq-cat <jaq.cat@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "*"
